version: "3"
services:
  server:
    build: .
    container_name: bia
    ports:
      - 80:8080
    environment:
      DB_USER: postgres
      DB_PWD: NAh}q|bVW:b*Zk52hV8aLX5VXu
      DB_HOST: bia-db.cp8oyae2mpyk.us-east-1.rds.amazonaws.com
      DB_PORT: 5432

